// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjE64PRSTkrnur0Xl85QbQ9Lglf7Nyyas',
    appId: '1:637082749257:web:bc50e318243d017422b298',
    messagingSenderId: '637082749257',
    projectId: 'final-exam-9341b',
    authDomain: 'final-exam-9341b.firebaseapp.com',
    storageBucket: 'final-exam-9341b.appspot.com',
    measurementId: 'G-X2MK4YX8BM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdSK_3WHuId9jUMqjak_k7GoTjNzDo1CI',
    appId: '1:637082749257:android:c50da277ebe761c322b298',
    messagingSenderId: '637082749257',
    projectId: 'final-exam-9341b',
    storageBucket: 'final-exam-9341b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0h3nkj4Tih6G3ndtFhrDeFygPZnLppZM',
    appId: '1:637082749257:ios:5f5405748b6873cd22b298',
    messagingSenderId: '637082749257',
    projectId: 'final-exam-9341b',
    storageBucket: 'final-exam-9341b.appspot.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0h3nkj4Tih6G3ndtFhrDeFygPZnLppZM',
    appId: '1:637082749257:ios:b4ef86a0cf91e22c22b298',
    messagingSenderId: '637082749257',
    projectId: 'final-exam-9341b',
    storageBucket: 'final-exam-9341b.appspot.com',
    iosBundleId: 'com.example.finalExam.RunnerTests',
  );
}
